# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dce307432c90242f38795d254cdf29b8df75f0bd065086b7ce10e507ab8137b59062d704a655ee4a1ebcdf1a4432ee61708e4a487f527a61b6532884ec67e61

test:
  secret_key_base: 349336ab89eecd7ce3ee827682976b8b8e481dadcadf51ef524b2bddd373255b216dc6cadb65ee6228a0cdcca9b819dd2f3ef00ddb1cc426ac9cfaa09bd8685a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
